apiVersion: apps/v1
kind: Deployment
# metadata are assigned to the Deployment itself
metadata:
  name: <deployname>
  labels:
    app: <appname>
    # the spec controls running pods and provides a template for new pods
spec:
# for running pods, how many to keep running
  replicas: 0 
# how to find the set of pods to control
  selector:
    matchLabels:
      app: <name of pods to match>
# the template for creating new pods
  template:
# these metadata go on the pods, and are used above by the deployment to control them...hence must match!
    metadata:
      labels:
        app: <name of pods must match above>
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "<metrics scrape port>"
        prometheus.io/path: "/metrics"
# this spec is how to build the container for each pod, its image, resources, and port assignments
    spec:
      containers:
      - name: <container name not pod name>
        imagePullPolicy: Always
        # image: index.docker.io/cwiecha/demoapp:latest
        image: <image name in index.docker.io qualified with username>
        # image: index.docker.io/python:latest
        ports:
        - containerPort: <port to route requests to, doesn't matter for this demo>
        resources:
          requests:
            cpu: 200m
